---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: macos
    driver:
      box: macos1012
      box_url: file:///Users/misheska/box/macos1012-vbox5.1.8-0.1.10.box
      vm_hostname: false
      cache_directory: false

suites:
  - name: default
    run_list:
      - recipe[box_macos_settings::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

  - name: non-default
    run_list:
      - recipe[box_macos_settings_test::non_default]
    verifier:
      inspec_tests:
        - test/smoke/non-default
    attributes:

  - name: macos-hostname-multi
    run_list:
      - recipe[box_macos_settings_test::macos_hostname_multi]
    verifier:
      inspec_tests:
        - test/smoke/macos-hostname-multi
    attributes:

  - name: macos-hostname
    run_list:
      - recipe[box_macos_settings_test::macos_hostname]
    verifier:
      inspec_tests:
        - test/smoke/macos-hostname
    attributes:
